version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: chatty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: minio server ./docker/minio/data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    ports:
      - 9000:9000
    volumes:
      - ./docker/minio/data:/var/lib/minio/data