version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: chatty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
