# Generated by Django 3.0.6 on 2020-06-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0002_auto_20200606_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
