# Generated by Django 3.0.6 on 2020-08-21 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatty', '0003_delete_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_hand_cents', models.IntegerField(default=0, verbose_name='Money not in investments (cents)')),
            ],
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='The symbol of the stock')),
                ('price_cents', models.IntegerField(verbose_name='Price (in cents) stock is bought at')),
                ('quantity', models.IntegerField(verbose_name='Number of stocks bought')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time the asset was purchased')),
                ('sold_at', models.DateTimeField(null=True, verbose_name='When asset was sold')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund', to='chatty.Fund')),
            ],
        ),
    ]
