# Generated by Django 3.0.6 on 2020-08-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0004_fund_stockholding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder', to='chatty.Fund'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When the post was created')),
                ('message', models.CharField(max_length=200, verbose_name='The content of the post')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund', to='chatty.Fund')),
            ],
        ),
    ]
