# Generated by Django 3.0.6 on 2020-08-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0005_auto_20200827_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='chatty.Fund'),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='chatty.Fund'),
        ),
    ]
