# Generated by Django 3.0.6 on 2020-09-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0006_auto_20200827_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When the article was created')),
                ('text', models.TextField(verbose_name='The long form content of the article')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='chatty.Fund')),
            ],
        ),
    ]
