# Generated by Django 3.0.6 on 2020-09-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When the article was created')),
                ('file_name', models.TextField(verbose_name='The filename of where the video can be retrieved from')),
                ('description', models.TextField(null=True, verbose_name='A description of what the video is about')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='chatty.Fund')),
            ],
        ),
    ]
