# Generated by Django 3.0.6 on 2020-11-17 01:37

from django.db import migrations, models
import roz.custom_storage


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0009_auto_20201002_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.CharField(default='NONAME PROVIDED', max_length=100, unique=True, verbose_name='The name of the fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=roz.custom_storage.VideoStorage(), upload_to='', verbose_name='The video file instance'),
        ),
    ]
