# Generated by Django 3.0.6 on 2020-11-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0010_auto_20201117_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fund',
        ),
        migrations.AddField(
            model_name='article',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='chatty.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Determines if the post is not to be shown'),
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='chatty.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=200, verbose_name='The content of the post'),
        ),
    ]
